### ISSUE TITLE
Wrong commit sha to find tag for

### ISSUE THREAD

**Issue by KnisterPeter** [goreleaser/goreleaser-action#315] opened 2021-11-22 13:47 UTC
If goreleaser-action runs with a workdir option, the tag is taken from the wrong directory.
This does fail if using submodules

https://github.com/goreleaser/goreleaser-action/blob/5df302e5e9e4c66310a6b6493a8865b12c555af2/src/main.ts#L32

**Comment by caarlos0** [comment] 2021-11-29 23:17
you are trying to release the submodule from the parent project?

not sure I understand what you're trying to do...

**Comment by KnisterPeter** [comment] 2021-11-30 08:02
What we are trying is this:

```
git-project  # <--- root where the tag is taken from
+--> submodule   # <--- workdir to run goreleaser on
```

We use `goreleaser-actions` to create a release. We do set the `workdir` to `submodule`, because it's the submodule we want to create a release for.
The action, before going into the submodule and execute there, does fetch information from the top-level.

Does that explain our case a bit better?

**Comment by caarlos0** [comment] 2021-11-30 12:34
yes.

that is not supported... 

you should probably have a release process for each submodule in their own project (and tag them instead of the parent).

closing as working as intended.

**Closed by caarlos0** 2021-11-30 12:34 UTC
Labels: bug
